// TODO (pdakin): Making everything client-side rendered is a hack to allow ThemeProvider
// compatibility with Next 13.
// Consider reverting to pages/ pattern if there are too many compatiblity issues.
"use client";

import './globals.css'
import { Inter } from 'next/font/google'

import Theme from './theme'
import { ThemeProvider } from '@mui/material/styles';

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // TODO (pdakin): Should the header component live in the root layout?
  return (
    <ThemeProvider theme={Theme}>
      <html lang="en">
        <body className={inter.className}>
          {children}
        </body>
      </html>
    </ThemeProvider>
  )
}
