// TODO (pdakin): Making everything client-side rendered is a hack to allow ThemeProvider
// compatibility with Next 13.
// Consider reverting to pages/ pattern if there are too many compatiblity issues.
"use client";

import "./globals.css";

import Theme from "./theme";
import { ThemeProvider } from "@mui/material/styles";

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ThemeProvider theme={Theme}>
      <html lang="en">
        <body suppressHydrationWarning={true}>{children}</body>
      </html>
    </ThemeProvider>
  );
}
